version: "3.8"

networks:
  doris-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  fe:
    image: apache/doris:fe-4.0.2
    hostname: fe
    container_name: doris-fe
    environment:
      - FE_SERVERS=fe1:172.28.0.10:9010
      - FE_ID=1
    ports:
      - "8030:8030"
      - "9010:9010"
      - "9030:9030"
    networks:
      doris-net:
        ipv4_address: 172.28.0.10

  be:
    image: apache/doris:be-4.0.2
    hostname: be
    container_name: doris-be
    depends_on:
      - fe
    environment:
      - FE_SERVERS=fe1:172.28.0.10:9010
      - BE_ADDR=172.28.0.11:9050
    ports:
      - "9050:9050"
    networks:
      doris-net:
        ipv4_address: 172.28.0.11
