version: "3.8"

networks:
  doris-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  fe:
    image: apache/doris:fe-4.0.2
    hostname: fe
    container_name: doris-fe
    environment:
      - FE_SERVERS=fe1:172.28.0.10:9010
      - FE_ID=1
    volumes:
      - ./doris/fe/meta:/opt/apache-doris/fe/doris-meta
      - ./doris/fe/log:/opt/apache-doris/fe/log
    ports:
      - "8030:8030"
      - "9010:9010"
      - "9030:9030"
    networks:
      doris-net:
        ipv4_address: 172.28.0.10

  be:
    image: apache/doris:be-4.0.2
    hostname: be
    container_name: doris-be
    depends_on:
      - fe
    environment:
      - FE_SERVERS=fe1:172.28.0.10:9010
      - BE_ADDR=172.28.0.11:9050
    volumes:
      - ./doris/be/storage:/opt/apache-doris/be/storage
      - ./doris/be/log:/opt/apache-doris/be/log
    ports:
      - "9050:9050"
    networks:
      doris-net:
        ipv4_address: 172.28.0.11
  spark:
    build:
      context: ./spark
    image: doris-spark-jupyter:3.5.7
    container_name: doris-spark
    depends_on:
      - fe
      - be
    networks:
      doris-net:
        ipv4_address: 172.28.0.20
    volumes:
      - ./spark:/opt/spark-app  
    environment:
    - HOME=/opt/spark-app
    - JUPYTER_RUNTIME_DIR=/tmp/jupyter/runtime
    - JUPYTER_DATA_DIR=/tmp/jupyter/data
    - JUPYTER_CONFIG_DIR=/tmp/jupyter/config
    ports:
      - "8888:8888"
    command:
      [
        "jupyter",
        "notebook",
        "--ip=0.0.0.0",
        "--port=8888",
        "--no-browser",
        "--NotebookApp.token=",
        "--NotebookApp.password="
      ]